Y2Z/monolith

Cargo.toml
src/http.rs
src/main.rs

Increase request timeout to 10 seconds

---

Cargo.toml
README.md
src/html.rs
src/http.rs
src/lib.rs
src/main.rs
src/utils.rs

move regex::new() to lazy static block and refactor code and cargo fmt and cargo clippy

lazy init regex refcator some code cargo clippy and cargo fmt

---

Cargo.toml
src/main.rs

@robatipoor please let me know if you're okay with the way you're credited

Add robatipoor to list of authors

---

Cargo.toml
src/html.rs

Can be tested using this page: https://cloudfour.com/examples/img-currentsrc/

Add support for picture elements

---

.travis.yml
appveyor.yml

please enable repo in travic and appveyor and publish crate in crates.io

add config travic and appvayor

---

src/http.rs

Add basic verbose output

---

Cargo.toml
README.md
src/html.rs
src/http.rs
src/main.rs

Add flag for silent mode

---

src/html.rs
src/http.rs
src/main.rs
src/tests/http.rs
src/tests/mod.rs

Properly handle 30x redirects

---

README.md

add related projects section

---

src/html.rs
src/http.rs
src/main.rs
src/tests/html.rs
src/tests/http.rs

the cache is threaded through all functions that use it, as an extra parameter

Use HashMap as cache to minimize the number of HTTP requests

---

.travis.yml
Makefile

Add --locked flag to the cargo build/test

---

.travis.yml

Needs to be merged into `master` urgently and all outstanding PRs rebased against this commit in order for them to pass the CI/CD pipeline

let nightly Rust always pass Travis' checks

---

src/html.rs
src/lib.rs
src/macros.rs

this macro replaces EMPTY_STRING

implement str!() macro

---

Cargo.lock
Cargo.toml
src/html.rs
src/tests/html.rs

Get rid of integrity attributes

---

src/args.rs
src/html.rs
src/http.rs
src/js.rs
src/tests/html.rs

Hi,
I added small refactorings to codebase. They should not change any behavior of this program.
- Reduce allocations (e.g. prefer `&str` to `String`)
- Reduce redundant code (e.g. unnecessary type annotation)
- Use slice instead of array not to hard-code number of elements of array constant

Refactorings

---

README.md
src/args.rs
src/html.rs
src/main.rs

Add option for custom network request timeout

---

.travis.yml
Dockerfile
README.md

add Dockerfile

---

src/html.rs
src/tests/html/get_node_name.rs

Revamp is_icon() and get_node_name()

---

src/html.rs

Empty SVG nodes when excluding images

---

src/css.rs
src/tests/css/embed_css.rs

Fix css unit sign bug

---

.github/workflows/cd.yml

Make the pipeline build and upload armhf executable with every new release

---

README.md
docs/arch/0002-noscript-nodes.md
docs/arch/0005-asset-minimization.md

Let me know what you think @Alch-Emi 
If we accept and implement this, #60 will be <b>r</b>esolved

Propose ADR-0002 (NOSCRIPT nodes)

---

src/html.rs

Embed SVG IMAGE assets

---

src/main.rs

Only attempt to remove credentals from HTTP(S) URLs

---

README.md

Add FreeBSD installation instructions to README.md

---

Cargo.lock
Cargo.toml

update clap 2.33.1 -> 2.33.3

---

src/tests/html/has_favicon.rs

remove unused import opts::Options;

---

README.md
docs/arch/0003-network-request-timeout.md
docs/arch/0005-asset-minimization.md
docs/arch/0006-reload-and-location-meta-tags.md
docs/arch/0007-network-errors.md
src/css.rs
src/html.rs
src/main.rs
src/opts.rs
src/tests/utils/retrieve_asset.rs
src/utils.rs

Account for network errors

---

Cargo.lock
Cargo.toml
src/html.rs
src/tests/html/embed_srcset.rs

Fix srcset parsing

---

src/html.rs
src/tests/html/walk_and_embed_assets.rs

Relates to #60, covers first half of NOSCRIPT ADR introduced in #91

Process contents of NOSCRIPT tags

---

Makefile
src/css.rs
src/html.rs
src/js.rs
src/main.rs
src/opts.rs
src/tests/cli/local_files.rs
src/tests/cli/mod.rs
src/tests/cli/unusual_encodings.rs
src/tests/data/unusual_encodings/iso-8859-1.html
src/utils.rs

Forcefully set document's charset to UTF-8

---

README.md

Add Monk to related projects in README.md

---

Cargo.lock
Cargo.toml
src/utils.rs

Don't remember for sure, but I think it was to work around a bug in reqwest;  likely no longer needed, but still could use this code as a general improvement.  Will keep open for now.

Rewrite part of function retrieve_asset, include support for brotli and deflate

---

src/main.rs

the commit rewrite a small part of the input argument handling, trying
to follow besr rust practices.
We get rid of a variable and of a mutable reference while keeping the
code a bit more coincise.

rewrite small part of the input argument handling

---

src/main.rs
tests/cli/data_url.rs

Parse XML documents, save non-HTML and non-XML targets unparsed

---

README.md

Since I use scoop, added scoop install to readme

Scoop as install source

---

README.md

Get rid of outdated related projects in README

---

README.md

Added the section right below the one for similarly-minded Guix, but happy to place this elsewhere in the file if preferred.

Add installation instructions for NixPkgs

---

README.md

I'm sorry, I made a mistake in the Actor name when creating the original PR.

fix: the Actor name.
