Y2Z/monolith

snap/snapcraft.yaml

Hello. I'm Alan, and I work for Canonical on [Snapcraft](https://snapcraft.io/), an app store for Linux used by many high profile and indie developers.
This PR adds support for building a [snap](https://snapcraft.io/) of monolith. I've tested it on my Ubuntu laptop by cloning this branch in a folder and doing:-
```
snap install snapcraft
snap install multipass
cd monolith
snapcraft
```
This built a snap which can work on numerous Linux distributions. I tested it with:
```
snap install monolith_0+git.27f1411_amd64.snap --dangerous
```
(`--dangerous` is required because the snap is being 'side-loaded' without being checked/signed by the [snap store](https://snapcraft.io/store))
I registered the name `monolith` in the snap store and pushed these builds to the edge channel. Users can test …

Add snapcraft yaml

---

.travis.yml
Cargo.toml
README.md
appveyor.yml
src/html.rs
src/http.rs
src/main.rs
src/utils.rs

Summary of work:
- Added new option `-I` for cutting the cord
- Added new option `-c` for ignoring styles
- Added new option `-f` for disabling iframes
- Changed icons' `href` attribute to be `""` instead of empty PNG when `--no-images` is provided
- Enabled format check in the pipeline
- Added more tests
Resolves #6

Add CSP isolation, no CSS and no iframe options

---

src/http.rs

Planning to add fancy tree indentation in the output to better visualize what asset came from where

Get rid of brackets around URLs

---

src/html.rs
src/http.rs
src/main.rs
src/tests/html.rs
src/tests/http.rs

This pull request implements a shared reqwest client for HTTP requests.
This enables us to use a single HTTP connection for downloading all resources within a single ip instead of initiating a new connection for each resource, leading to efficiency improvements.  This also simplifies argument passing a little, specifically the passing of user agent and security arguments, which can be built into the client at the beginning instead of passed all the way down through the evaluation tree.  It may also be worth nothing that this is the recommended behavior in the [reqwest docs][1]
[1]: https://docs.rs/reqwest/0.10.0-alpha.2/reqwest/index.html#making-a-get-request

Use a shared client for HTTP requests

---

.travis.yml
appveyor.yml
src/http.rs
src/tests/utils.rs
src/utils.rs

This solves the problem that can often be seen where web fonts get included using IE6-8 fix that has duplicate font URL in CSS with `?#` at the end. Caching should always exclude fragment (`#...`) since it never gets sent over the network, however I'm still on the fence with r-trimming empty query (`?`), as I'm not entirely sure the server sees the same request with a question mark at the end as without.

use clean URLs as hashmap keys

---

src/html.rs

The way this patch works is by resolving any `data-src` tags on images in
the same way as normal source tags are resolved.  It is assumed that most
lazy-load libraries will use this tag, and that if this tag is set, then it is a
URL that is in use.
I'm not sure if this is an oversimple solution, but it does seem to resolve lazy loading the the two sites given in the PR that this would close, #16.

Add support for lazy loaded images

---

Cargo.toml
src/html.rs
src/http.rs
src/lib.rs
src/main.rs
src/utils.rs

This PR migrates monolith to [Rust2018 edition](https://doc.rust-lang.org/stable/edition-guide/rust-2018/edition-changes.html) from current old Rust2015 edition. Rust2018 is a newer spec of Rust programming language as you know. Changes are mainly for module imports/exports and done by `cargo fix --edition`/`cargo fix --edition-idioms`.
I confirmed `cargo run` works the same as previous and all tests passed.

Migrate to Rust2018 edition

---

Cargo.lock
Cargo.toml
src/html.rs
src/http.rs
src/main.rs
src/tests/html.rs
src/tests/http.rs
src/utils.rs

I updated `reqwest` dependency from v0.9 to [v0.10](https://github.com/seanmonstar/reqwest/releases/tag/v0.10.0).
Effects are as follows:
- **Compile targets**: 220
- **Build time**: `cargo build --release  1264.95s user 39.72s system 335% cpu 6:29.14 total`
- **Binary size**: 6578568 bytes
- **Compile targets**: 170
- **Build time**: `cargo build --release  1130.64s user 32.15s system 359% cpu 5:23.69 total`
- **Binary size**: 6107088 bytes
- **Compile targets**: 1.29x smaller
- **Build time**: 1.23x faster
- **Binary size**: 1.07x smaller
reqwest 0.10 now separates its functionalities into several features. I picked necessary features (all features list can be found [here](https://github.com/seanmonstar/reqwest/blob/b159963f6c19d8607a38f1a17c45b38fa8b4d4d2/Cargo.toml#L25-L48)) so number …

Upgrade reqwest to v0.10.0 for better binary size and build time

---

snap/snapcraft.yaml

This changes the build slightly. If snapcraft is triggered when there is a new tagged release in the project github release page, and it's newer than the version in the Snap Store beta channel, we build that stable release. If however, the latest stable release in github releases is already the same as the Snap Store beta channel, then we build the tip of master.
This gives a couple of advantages. 
* One yaml can be used to build tip-of-git snaps, and stable releases alike
* Closing the beta channel in the Snap Store will mean the next triggered build will re-build whatever the last stable release is. This is useful to force a rebuild of the stable version in case a dependency (not that there are many) has a security issue.
We also now set the version dynamically based on the git tags.

Update snapcraft configuration

---

src/html.rs

This PR has two changes:
By using `match` statement and enum, it can check exhaustiveness of the variations. Since `<link>` has many `rel` variations, checking the exhaustiveness would be useful. This is just a refactoring and will not change the behavior at all.
I observed following warning when I opened a generated HTML file:
Monolith embeds all resources as data URLs so preloading and prefetching are not necessary. This PR modifies a generated HTML not to preload/prefetch them by clearing `href` property.

Improve handling preload links and white spaces in attribute values

---

src/main.rs

Hi, I added refactorings and fixes to `main.rs`
Addressed issues:
- when specified URL was invalid, it exited successfully with doing nothing. Users could not know what happened and why it did not work
- it exited successfully even if invalid User-Agent value is specified
- it created file twice on `--output` option specified. It may cause an issue when some file watcher (e.g. FsEvents on macOS) is watching the directory
Improvements:
- handle errors with `Result::expect` consistently it correctly exits with non-zero status on error and it leaves a helpful error message for users
- define `Output` enum for handling both stdout and file outputs in the same way in `main()` logic
Note:
These changes would make some conflicts with #100. I can resolve them so please let me know if some help is …

Refactoring for main.rs to address several issues

---

README.md
src/main.rs

Fixes #103 
With this PR `monolith` command will look `$https_proxy` and `$http_proxy` environment variables like other major CLI tools (e.g. `pip`, `apt`, ...).

Support HTTP and HTTPS proxies

---

README.md
src/main.rs

This PR reverts #106 and adds small instruction to README.md for proxies.
After #106 was merged, I've found that reqwest supports HTTP and HTTPS proxies by default. We don't need to add any code to support it. It means that they are already supported in current version.
Though I'm not under proxy environment, I confirmed `$https_proxy` is referred by confirming an error:
```
> https_proxy=http://localhost cargo run -- https://example.com
thread 'main' panicked at 'Could not retrieve assets in HTML: reqwest::Error { kind: Request, url: "https://example.com/", source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to …
```

Revert #106 since reqwest supports system proxies by default

---

README.md
src/args.rs
src/html.rs
src/tests/html.rs

Merging this PR will let monolith save pages that use framesets (e.g. http://www.maths.surrey.ac.uk/explore/nigelspages/frame2.htm), as well as discard them when the `-f` flag is provided.

Treat frames the same way as iframes

---

src/html.rs
src/tests/html.rs

This PR adds support for embedding images found in `<body background="some-image.gif">`.
It's not an HTML5 feature, but rather a legacy leftover from HTML4 that's still supported by browsers today.
Had to be added in order to fully support saving pages from https://spacejam.com

Account for legacy BODY background="" attribute

---

docs/arch/0004-asset-integrity-check.md

Currently all links get their `integrity` attribute removed without being validated prior. That may let rogue scripts end up in the final document.

Propose ADR 0004: Asset integrity check

---

snap/snapcraft.yaml

@popey hey Alan, could you please check to see if it builds now on armhf if you get a minute? I remember there were some issues with it -- was wondering if the new(er) version of Rust and dependencies makes it go smooth now.

Add armhf target to snapcraft.yaml

---

Cargo.lock
Cargo.toml
README.md

Also bumps project version number to 2.4.0

Update Cargo.toml for publishing on crates.io

---

Cargo.toml
LICENSE
README.md

At the time of creating this project, The Unlicense, in my understanding was the most permissive and no-strings-attached way of sharing code with the world. My intention was to contribute to universal Rust's codebase in the most selfless way, let people borrow code from this code base and use it without having to waste energy on thinking about licenses or credits. Many people expressed their aversion towards The Unlicense, suggesting it being unprofessionally written and one of the worst licenses one could choose for a project.
I wouldn't want to take this project out of the public domain at this point, due to way too many people using this tool. My most current research shows that CC0-1.0 appears to be a much more mature and overall better way of releasing code into the public domain. …

Change project license to CC0 1.0 Universal (CC0 1.0)

---

src/css.rs
src/tests/css/embed_css.rs

Remove optional trailing space from CSS idents

---

.github/workflows/cd.yml

Downgrade AArch64 CD job from Ubuntu 20.04 to Ubuntu 18.04

---

Dockerfile
utils/run-in-container.sh

By using a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) the Docker image size can be reduced significantly.
Before it used 1.88GB of disk space now it's only 23.5MB.

Reduce size of Docker image

---

src/html.rs
tests/cli/data_url.rs
tests/cli/local_files.rs
tests/html/compose_csp.rs
tests/html/serialize_document.rs

Some websites require this in order to let its JS operate.

Include unsafe-eval origin for isolated documents

---

README.md

The monk project has recently moved to Github! Just changing the link in the "Related Projects" section of the readme to the new repository.

Updated monk project link

---

Cargo.lock
Cargo.toml

This will reduce the monolith binary size by ~15%.

disable unnecessary/unused regex features to reduce binary size

---

README.md
src/cookies.rs
src/lib.rs
src/main.rs
src/opts.rs
src/utils.rs
tests/cli/unusual_encodings.rs
tests/cookies/cookie/is_expired.rs
tests/cookies/cookie/matches_url.rs
tests/cookies/cookie/mod.rs
tests/cookies/mod.rs
tests/cookies/parse_cookie_file_contents.rs
tests/mod.rs
tests/opts.rs

```
127.0.0.1   FALSE   /   FALSE   0   USER_TOKEN  in
```
7 tab-separated fields: domain, tailmatch, path, secure, expires, name, value.

Cookie file support

---

.github/workflows/cd.yml

ubuntu-18.04 has been deprecated from [supported ubuntu versions](https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners)

fix: bump CD workflow runner to ubuntu-20.04

---

README.md
dist/run-in-container.sh

This PR fixes a minor issue in README:
```
🦎 ✔ ~/dev/github/monolith [master|✔]
11:40 $ docker build -t Y2Z/monolith .
[+] Building 0.0s (0/0)                                                                                                              docker:default
ERROR: failed to solve: invalid reference format: repository name must be lowercase
🦎 ✘-1 ~/dev/github/monolith [master|✔]
11:40 $ docker build -t y2z/monolith .
```

🩹 fix README to prevent 'ERROR: failed to solve: invalid reference format: repository name must be lowercase'

---

README.md

I did not have cargo installed on my system when I first tried to build the repo from a fresh git clone (I had not noticed it was a rust project), and it wasn't called out as a dependency for installation from source. I've added it as a noted dependency with some quick, collapsible installation instructions I followed to get it installed.

Add cargo setup to README

---

README.md

Flox can currently install monolith into a development environment, and seems to be working.
The package itself is based on that coming from nixpkgs, and follows it quite closely.
Currently, Flox doesn't have a webpage to preview the package version et al.
So, instead I just linked to the website itself.

Add flox installation option

---

Cargo.toml
src/url.rs
src/utils.rs
tests/url/get_referer_url.rs
tests/url/mod.rs
tests/url/referer_url.rs

to mimic more-browser-like-behavior on loading page resources. Sometimes their response depends on `referer` header.
e.g. I faced with the problem to load font data for page, because it was protected for "direct" loading, got `401`, but with the `referer` header it looks like request from browser.

add HTTP referer header for resource requests

---

Cargo.lock
Cargo.toml

```bash
$ ldd ./target/debug/monolith
linux-vdso.so.1 (0x00007ffcdf3f0000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x0000778480ac4000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007784809db000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000077847f400000)
/lib64/ld-linux-x86-64.so.2 (0x0000778480b09000)
```
No openssl dynamic link, and the tests pass on my machine.
Unfortunately, it will be necessary to manually keep the openssl version in sync with what reqwest wants.

Link openssl statically - fixes #340

---

Cargo.toml

Hey, I'm the maintainer of the [monolith package](https://archlinux.org/packages/extra/x86_64/monolith/) for Arch Linux :wave:
I saw that in the latest version OpenSSL is being linked statically, which is something that I wanted to avoid for the package. I was able to do it by using `OPENSSL_NO_VENDOR=1` flag but thought it would be better to add a feature flag for it so that I can do `--no-default-features` next time :)
Cheers!

Support disabling vendored OpenSSL while building

---

src/utils.rs

Only send Referer HTTP header if the parent URL's scheme is http(s)

---

src/html.rs
tests/html/mod.rs
tests/html/parse_link_type.rs

Add support for parsing multiple link type (rel) attribute values

---

src/html.rs
tests/html/is_favicon.rs
tests/html/mod.rs
tests/html/parse_link_type.rs

Add support for embedding apple-touch-icons

---

Cargo.toml
src/core.rs
src/html.rs
tests/cli/base_url.rs
tests/cli/basic.rs
tests/cli/data_url.rs
tests/cli/local_files.rs
tests/cli/noscript.rs
tests/cli/unusual_encodings.rs

Automtically add "robots=none" META-tag to every saved document
